--Remove modifer, Gain new modifier
MagicDragonTransform = {}

MagicDragonTransform.modifier_magic_dragon_magic_form = function(hCaster)
	local hModifier = hCaster:FindModifierByName("modifier_magic_dragon_magic_form") or hCaster:FindModifierByName("modifier_magic_dragon_undead_form") or hCaster:FindModifierByName("modifier_magic_dragon_ice_form") or hCaster:FindModifierByName("modifier_magic_dragon_fire_form") or hCaster:FindModifierByName("modifier_magic_dragon_lightning_form") or hCaster:FindModifierByName("modifier_magic_dragon_anti_magic_form")
	hModifier:Destroy()
	hCaster:AddNewModifier(hCaster, nil, "modifier_magic_dragon_magic_form", {})
	
	local hHide = hCaster:GetAbilityByIndex(1)
	local iHideLevel = hHide:GetLevel()
	hCaster:RemoveAbility(hHide:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_hide")	
	local hHideNew = hCaster:AddAbility("magic_dragon_green_dragon_hide")
	hHideNew:SetLevel(iHideLevel)
	
	local hBreath = hCaster:GetAbilityByIndex(2)
	local iBreathLevel = hBreath:GetLevel()
	hCaster:RemoveAbility(hBreath:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_breath")	
	local hBreathNew = hCaster:AddAbility("magic_dragon_green_dragon_breath")
	hBreathNew:SetLevel(iBreathLevel)
	
	local hRoar = hCaster:GetAbilityByIndex(0)
	local iRoarLevel = hRoar:GetLevel()
	hCaster:RemoveAbility(hRoar:GetName())
	local hRoarNew = hCaster:AddAbility("magic_dragon_green_dragon_roar")
	hRoarNew:SetLevel(iRoarLevel)
end

MagicDragonTransform.modifier_magic_dragon_undead_form = function(hCaster)
	local hModifier = hCaster:FindModifierByName("modifier_magic_dragon_magic_form") or hCaster:FindModifierByName("modifier_magic_dragon_undead_form") or hCaster:FindModifierByName("modifier_magic_dragon_ice_form") or hCaster:FindModifierByName("modifier_magic_dragon_fire_form") or hCaster:FindModifierByName("modifier_magic_dragon_lightning_form") or hCaster:FindModifierByName("modifier_magic_dragon_anti_magic_form")
	hModifier:Destroy()
	hCaster:AddNewModifier(hCaster, nil, "modifier_magic_dragon_undead_form", {})
	
	local hHide = hCaster:GetAbilityByIndex(1)
	local iHideLevel = hHide:GetLevel()
	hCaster:RemoveAbility(hHide:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_hide")	
	local hHideNew = hCaster:AddAbility("magic_dragon_ghost_dragon_hide")
	hHideNew:SetLevel(iHideLevel)
	
	local hBreath = hCaster:GetAbilityByIndex(2)
	local iBreathLevel = hBreath:GetLevel()
	hCaster:RemoveAbility(hBreath:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_breath")	
	local hBreathNew = hCaster:AddAbility("magic_dragon_ghost_dragon_breath")
	hBreathNew:SetLevel(iBreathLevel)
	
	local hRoar = hCaster:GetAbilityByIndex(0)
	local iRoarLevel = hRoar:GetLevel()
	hCaster:RemoveAbility(hRoar:GetName())
	local hRoarNew = hCaster:AddAbility("magic_dragon_ghost_dragon_roar")
	hRoarNew:SetLevel(iRoarLevel)
end

MagicDragonTransform.modifier_magic_dragon_ice_form = function(hCaster)
	local hModifier = hCaster:FindModifierByName("modifier_magic_dragon_magic_form") or hCaster:FindModifierByName("modifier_magic_dragon_undead_form") or hCaster:FindModifierByName("modifier_magic_dragon_ice_form") or hCaster:FindModifierByName("modifier_magic_dragon_fire_form") or hCaster:FindModifierByName("modifier_magic_dragon_lightning_form") or hCaster:FindModifierByName("modifier_magic_dragon_anti_magic_form")
	hModifier:Destroy()
	hCaster:AddNewModifier(hCaster, nil, "modifier_magic_dragon_ice_form", {})
	
	local hHide = hCaster:GetAbilityByIndex(1)
	local iHideLevel = hHide:GetLevel()
	hCaster:RemoveAbility(hHide:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_hide")	
	local hHideNew = hCaster:AddAbility("magic_dragon_blue_dragon_hide")
	hHideNew:SetLevel(iHideLevel)
	
	local hBreath = hCaster:GetAbilityByIndex(2)
	local iBreathLevel = hBreath:GetLevel()
	hCaster:RemoveAbility(hBreath:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_breath")	
	local hBreathNew = hCaster:AddAbility("magic_dragon_blue_dragon_breath")
	hBreathNew:SetLevel(iBreathLevel)
	
	local hRoar = hCaster:GetAbilityByIndex(0)
	local iRoarLevel = hRoar:GetLevel()
	hCaster:RemoveAbility(hRoar:GetName())
	local hRoarNew = hCaster:AddAbility("magic_dragon_blue_dragon_roar")
	hRoarNew:SetLevel(iRoarLevel)
end

MagicDragonTransform.modifier_magic_dragon_fire_form = function(hCaster)
	local hModifier = hCaster:FindModifierByName("modifier_magic_dragon_magic_form") or hCaster:FindModifierByName("modifier_magic_dragon_undead_form") or hCaster:FindModifierByName("modifier_magic_dragon_ice_form") or hCaster:FindModifierByName("modifier_magic_dragon_fire_form") or hCaster:FindModifierByName("modifier_magic_dragon_lightning_form") or hCaster:FindModifierByName("modifier_magic_dragon_anti_magic_form")
	hModifier:Destroy()
	hCaster:AddNewModifier(hCaster, nil, "modifier_magic_dragon_fire_form", {})
	
	local hHide = hCaster:GetAbilityByIndex(1)
	local iHideLevel = hHide:GetLevel()
	hCaster:RemoveAbility(hHide:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_hide")	
	local hHideNew = hCaster:AddAbility("magic_dragon_red_dragon_hide")
	hHideNew:SetLevel(iHideLevel)
	
	local hBreath = hCaster:GetAbilityByIndex(2)
	local iBreathLevel = hBreath:GetLevel()
	hCaster:RemoveAbility(hBreath:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_breath")	
	local hBreathNew = hCaster:AddAbility("magic_dragon_red_dragon_breath")
	hBreathNew:SetLevel(iBreathLevel)
	
	local hRoar = hCaster:GetAbilityByIndex(0)
	local iRoarLevel = hRoar:GetLevel()
	hCaster:RemoveAbility(hRoar:GetName())
	local hRoarNew = hCaster:AddAbility("magic_dragon_red_dragon_roar")
	hRoarNew:SetLevel(iRoarLevel)
end

MagicDragonTransform.modifier_magic_dragon_lightning_form = function(hCaster)
	local hModifier = hCaster:FindModifierByName("modifier_magic_dragon_magic_form") or hCaster:FindModifierByName("modifier_magic_dragon_undead_form") or hCaster:FindModifierByName("modifier_magic_dragon_ice_form") or hCaster:FindModifierByName("modifier_magic_dragon_fire_form") or hCaster:FindModifierByName("modifier_magic_dragon_lightning_form") or hCaster:FindModifierByName("modifier_magic_dragon_anti_magic_form")
	hModifier:Destroy()
	hCaster:AddNewModifier(hCaster, nil, "modifier_magic_dragon_lightning_form", {})
	
	local hHide = hCaster:GetAbilityByIndex(1)
	local iHideLevel = hHide:GetLevel()
	hCaster:RemoveAbility(hHide:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_hide")	
	local hHideNew = hCaster:AddAbility("magic_dragon_gold_dragon_hide")
	hHideNew:SetLevel(iHideLevel)
	
	local hBreath = hCaster:GetAbilityByIndex(2)
	local iBreathLevel = hBreath:GetLevel()
	hCaster:RemoveAbility(hBreath:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_breath")	
	local hBreathNew = hCaster:AddAbility("magic_dragon_gold_dragon_breath")
	hBreathNew:SetLevel(iBreathLevel)
	
	local hRoar = hCaster:GetAbilityByIndex(0)
	local iRoarLevel = hRoar:GetLevel()
	hCaster:RemoveAbility(hRoar:GetName())
	local hRoarNew = hCaster:AddAbility("magic_dragon_gold_dragon_roar")
	hRoarNew:SetLevel(iRoarLevel)
end

MagicDragonTransform.modifier_magic_dragon_anti_magic_form = function(hCaster)
	local hModifier = hCaster:FindModifierByName("modifier_magic_dragon_magic_form") or hCaster:FindModifierByName("modifier_magic_dragon_undead_form") or hCaster:FindModifierByName("modifier_magic_dragon_ice_form") or hCaster:FindModifierByName("modifier_magic_dragon_fire_form") or hCaster:FindModifierByName("modifier_magic_dragon_lightning_form") or hCaster:FindModifierByName("modifier_magic_dragon_anti_magic_form")
	hModifier:Destroy()
	hCaster:AddNewModifier(hCaster, nil, "modifier_magic_dragon_anti_magic_form", {})
	
	local hHide = hCaster:GetAbilityByIndex(1)
	local iHideLevel = hHide:GetLevel()
	hCaster:RemoveAbility(hHide:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_hide")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_hide")	
	local hHideNew = hCaster:AddAbility("magic_dragon_black_dragon_hide")
	hHideNew:SetLevel(iHideLevel)
	
	local hBreath = hCaster:GetAbilityByIndex(2)
	local iBreathLevel = hBreath:GetLevel()
	hCaster:RemoveAbility(hBreath:GetName())
	hCaster:RemoveModifierByName("modifier_magic_dragon_green_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_ghost_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_red_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_blue_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_black_dragon_breath")
	hCaster:RemoveModifierByName("modifier_magic_dragon_gold_dragon_breath")	
	local hBreathNew = hCaster:AddAbility("magic_dragon_black_dragon_breath")
	hBreathNew:SetLevel(iBreathLevel)
	
	local hRoar = hCaster:GetAbilityByIndex(0)
	local iRoarLevel = hRoar:GetLevel()
	hCaster:RemoveAbility(hRoar:GetName())
	local hRoarNew = hCaster:AddAbility("magic_dragon_black_dragon_roar")
	hRoarNew:SetLevel(iRoarLevel)
end


print("Magic Dragon initialized")