hHero = PlayerResource:GetPlayer(0):GetAssignedHero() 
hHero:FindAbilityByName("special_bonus_gold_income_25"):SetLevel(1)
print(hHero:FindAbilityByName("special_bonus_gold_income_25"):GetLevel())
hHero:RemoveAbility("special_bonus_exp_boost_30")
hHero:AddAbility("special_bonus_exp_boost_30")
print(hHero:FindAbilityByName("special_bonus_exp_boost_30"):GetLevel())
