
var tFunHeroInfo = {
	'spirit_breaker':{'sName':'astral_trekker', 'sCapitalName':'SpiritBreaker', 'bNewAvatar':false, 'bOld':true, 'bImba':true,},
	'shadow_demon':{'sName':'bastion', 'sCapitalName':'ShadowDemon', 'bNewAvatar':true, 'bOld':false, 'bImba':true,},
	'treant':{'sName':'intimidator', 'sCapitalName':'Treant', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'techies':{'sName':'persuasive', 'sCapitalName':'Techies', 'bNewAvatar':false, 'bOld':false, 'bImba':true,},
	'night_stalker':{'sName':'void_demon', 'sCapitalName':'NightStalker', 'bNewAvatar':false, 'bOld':true, 'bImba':false,},
	'tinker':{'sName':'terran_marine', 'sCapitalName':'Tinker', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'visage':{'sName':'magic_dragon', 'sCapitalName':'Visage', 'bNewAvatar':false, 'bOld':false, 'bImba':true,},
	'arc_warden':{'sName':'mana_fiend', 'sCapitalName':'ArcWarden', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'wisp':{'sName':'formless', 'sCapitalName':'Wisp', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'beastmaster':{'sName':'fluid_engineer', 'sCapitalName':'Beastmaster', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'enigma':{'sName':'telekenetic_blob', 'sCapitalName':'Enigma', 'bNewAvatar':false, 'bOld':false, 'bImba':true,},
	'dragon_knight':{'sName':'ramza', 'sCapitalName':'DragonKnight', 'bNewAvatar':true, 'bOld':false, 'bImba':true,},
	'oracle':{'sName':'cleric', 'sCapitalName':'Oracle', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'windrunner':{'sName':'pet_summoner', 'sCapitalName':'Windrunner', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'sven':{'sName':'felguard', 'sCapitalName':'Sven', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'pugna':{'sName':'el_dorado', 'sCapitalName':'Pugna', 'bNewAvatar':true, 'bOld':false, 'bImba':false,},
	'disruptor':{'sName':'hurricane', 'sCapitalName':'Disruptor', 'bNewAvatar':true, 'bOld':false, 'bImba':false,},
	'nevermore':{'sName':'capslockftw', 'sCapitalName':'Nevermore', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'omniknight':{'sName':'templar', 'sCapitalName':'Omniknight', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'meepo':{'sName':'spongebob', 'sCapitalName':'Meepo', 'bNewAvatar':true, 'bOld':false, 'bImba':false,},
	'tusk':{'sName':'hamsterlord', 'sCapitalName':'Tusk', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'juggernaut':{'sName':'exsoldier', 'sCapitalName':'Juggernaut', 'bNewAvatar':true, 'bOld':false, 'bImba':false,},
	'rubick':{'sName':'gambler', 'sCapitalName':'Rubick', 'bNewAvatar':false, 'bOld':true, 'bImba':false,},
	'life_stealer':{'sName':'old_lifestealer', 'sCapitalName':'LifeStealer', 'bNewAvatar':false, 'bOld':true, 'bImba':false,},
	'chaos_knight':{'sName':'rider', 'sCapitalName':'ChaosKnight', 'bNewAvatar':false, 'bOld':true, 'bImba':false,},
	'skywrath_mage':{'sName':'siglos', 'sCapitalName':'SkywrathMage', 'bNewAvatar':false, 'bOld':false, 'bImba':false,},
	'warlock':{'sName':'flame_lord', 'sCapitalName':'Warlock', 'bNewAvatar':false, 'bOld':true, 'bImba':false,},
	'keeper_of_the_light':{'sName':'conjurer', 'sCapitalName':'KeeperOfTheLight', 'bNewAvatar':false, 'bOld':true, 'bImba':false,},
	'spectre':{'sName':'avatar_of_vengeance', 'sCapitalName':'Spectre', 'bNewAvatar':false, 'bOld':true, 'bImba':false,},
//	'invoker':{'sName':'invoker_retro', 'sCapitalName':'Invoker', 'bNewAvatar':false, 'bOld':true, 'bImba':false,},
}